config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise for users
  # devise_for :users

  # our registration controller route
  devise_for :users, controllers: { registrations: 'registrations' }

  # active admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # products
  resources :product, only: %i[index show] do
    member do
      post :add_to_cart
      post :remove_item
    end
    collection do
      post :clear_cart
    end
  end

  get 'products/(:filter)', to: 'product#index', as: 'products'

  # categories
  resources :categories, only: %i[index show]

  # resources :carts, only: [:index]
  get 'cart', to: 'carts#index'

  # orders
  resources :orders, only: %i[index]

  # static pages
  resources :pages, only: [:show]
  get ':permalink', to: 'pages#permalink'

  # search
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end

  # stripe routes
  resources :charges, only: [:new, :create]

  # welcome page
  resources :welcome, only: [:index]
  # get 'welcome', to: 'welcome#index'
  # root route to the welcome page
  root to: 'welcome#index' 
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :title, presence: true, uniqueness: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :subtotal, presence: true
  validates :user, presence: true
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  # validates :quantity, :price, presence: true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  # empty model for static pages
  validates :title, :content, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  mount_uploader :picture, PictureUploader

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :title, :price, presence: true

  scope :newly_added, -> { order(created_at: :desc) }
  scope :updated,     -> { order(updated_at: :desc) }

  def self.sort_by(sort_param)
    case sort_param
    when 'newly_added'
      newly_added
    when 'updated'
      updated
    else
      all
    end
  end
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
# frozen_string_literal: true

class ProductVariant < ApplicationRecord
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :province, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController

  before_action :authenticate_user!

  def index
    # subtotal
    session[:subtotal] = subtotal
    session[:total] = total
  end

  def subtotal
    subtotal = 0
    @shopping_cart.each do |item|
      subtotal += item.price
    end

    subtotal
  end
  helper_method :subtotal

  # calculates the total amount to be paid for the order
  def total
    # @total = ((@total_tax_rate + 1) * session[:subtotal])
    @total = tax_amount + subtotal
  end

  # calculates taxes
  def tax_amount
    @province = current_user.province_id
    province = Province.find(@province)
    @gst = province.gst
    @pst = province.pst
    @hst = province.hst

    # sessions for taxes to be used in Order creation
    session[:gst] ||= @gst
    session[:pst] ||= @pst
    session[:hst] ||= @hst

    @total_tax_rate = @gst + @pst + @hst

    @total_tax_amount = (subtotal * @total_tax_rate).to_d
  end
end

app/controllers/product_controller.rb
# frozen_string_literal: true

class ProductController < ApplicationController
  # collection of all Products
  def index
    # @products = Product.order(:title)
    # Product.where("created_at >= ?", 1.week.ago.utc).order("DESC, created_at DESC")
    # @products = Product.order(:title).page(params[:page]).per(5)

    @products = Product.sort_by(params[:order]).page(params[:page]).per(5)
  end

  # Specific Product by ID
  def show
    @product = Product.find(params[:id])
  end

  # POST /product/:id/add_to_cart
  def add_to_cart
    id = params[:id].to_i
    # qty = params[:quantity].to_i
    session[:cart] << id unless session[:cart].include?(id)

    flash[:success] = 'Item has been added!'
    redirect_to root_url  
  end

  # Clears the shopping cart session
  #  POST /product/clear_cart
  def clear_cart
    session[:cart] = []
    flash[:info] = 'Cart has been emptied!'
    redirect_to root_url
  end

  # remove specific items from cart
  def remove_item
    cart_item_id = params[:id].to_i
    session[:cart].delete(cart_item_id)

    flash[:info] = 'Item has been removed!'
    redirect_to cart_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
# frozen_string_literal: true

module OrderItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/product/_product.html.erb
<p class="remove-bottom-margin" style="font-size: 12pt;"><%= product.title %></p>
<span><%= product.manufacturer %></span>
    
<% if show_details_link %>
    <%= link_to 'View Details', product %>
<% end %>
<br>

app/views/product/index.html.erb
<p>
  <%= link_to 'Home', '/' %> /
  <%= link_to 'Products', product_index_path %> /
</p>

<h5>Product List</h5>

<%= link_to 'New Products', products_path(order: :newly_added)%>
|
<%= link_to 'Updated Recently', products_path(order: :updated) %>

<%= render partial: 'product',
           collection: @products,
           locals: { show_details_link: true} %>

<br>
<%= paginate @products  %>

app/views/product/show.html.erb
<!--<%= render partial: 'product',
           object: @product,
           locals: { show_details_link: false} %>-->
<p>
  <%= link_to 'Home', '/' %> /
  <%= link_to 'Products', product_index_path %> /
  <%= @product.id %>
</p>

<div class="col s12 show_card">
  <div class="card horizontal">
    <div style="width: 500px;">
      <img class="show_image" src="<%= @product.image %>" alt="full image">
    </div>
    <div class="card-stacked">
      <div class="card-content">
      <h4 class="header"><%= @product.title %></h4>
        <div class="card-action"></div>
          <ul>
            <li><b>Description: </b> <%= @product.description %></li>
            <li><b>Price: </b> <%= number_to_currency @product.price %></li>
            <li><b>Categories: </b> 
              <% @product.product_categories.each do |cat| %>
                <%= link_to cat.category.title, cat.category %>
              <% end %>
            </li>
            <li><b>Manufacturer: </b> <%= @product.manufacturer %></li>
          </ul>
          <%= link_to add_to_cart_product_path(@product), method: :post, class: "btn waves-light" do %>
            Add to Cart<i class="material-icons right">shopping_cart</i>
          <% end %>
        </div>
    </div>
  </div>
</div>