config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise for users
  # devise_for :users

  # our registration controller route
  devise_for :users, controllers: { registrations: 'registrations' }

  # active admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # products
  resources :product, only: %i[index show] do
    member do
      post :add_to_cart
      post :remove_item
    end
    collection do
      post :clear_cart
    end
  end

  get 'products/(:filter)', to: 'product#index', as: 'products'

  # categories
  resources :categories, only: %i[index show]

  # resources :carts, only: [:index]
  get 'cart', to: 'carts#index'

  # orders
  resources :orders, only: %i[index]

  # static pages
  resources :pages, only: [:show]
  get ':permalink', to: 'pages#permalink'

  # search
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end

  # stripe routes
  resources :charges, only: [:new, :create]

  # welcome page
  resources :welcome, only: [:index]
  # get 'welcome', to: 'welcome#index'
  # root route to the welcome page
  root to: 'welcome#index' 
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  validates :title, presence: true, uniqueness: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :subtotal, presence: true
  validates :user, presence: true
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  # validates :quantity, :price, presence: true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  # empty model for static pages
  validates :title, :content, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  mount_uploader :picture, PictureUploader

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :title, :price, presence: true

  scope :newly_added, -> { order(created_at: :desc) }
  scope :updated,     -> { order(updated_at: :desc) }

  def self.sort_by(sort_param)
    case sort_param
    when 'newly_added'
      newly_added
    when 'updated'
      updated
    else
      all
    end
  end
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
# frozen_string_literal: true

class ProductVariant < ApplicationRecord
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :province, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, message| %>
    <div class="flash_div <%= name %>">
        <%= message %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer nav-colour">
    <div class="container" style="padding-bottom: 25px;">
        © 2018 Copyright - ShopForStuffs - Shane Fondeur
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- products/categories dropdown -->
<ul id="dropdown" class="dropdown-content">
  <li><a href="/product">Products</a></li>
  <li class="divider"></li>
  <li><a href="/categories">Categories</a></li>
  <li class="divider"></li>
</ul>

<!-- cart dropdown -->
<ul id="dropdown" class="dropdown-content">
  <% @shopping_cart.each do |x| %>
    <li>
        <span class="checkouttitle"><%= x.title %></span>
        <span class="checkoutprice"><%= number_to_currency x.price%></span>
    </li>
    <li class="divider"></li>
  <% end %>
  <% if @shopping_cart.size > 0 %>
    <%= link_to 'Checkout', cart_path, :class => "btn", :method => :get %>
    <li class="divider"></li>
    <%= link_to 'Empty Cart?', clear_cart_product_index_path, method: :post, class: "clear_cart_button"%>
  <% end %>
</ul>

<!-- Hamburger menu button side-nav content -->
<ul class="sidenav" id="mobile-demo">
  <li>
    <div class="center row">
      <div class="col s12 " >
        <div class="row">
          <div class="input-field col s6 s12">
            <%= render 'layouts/search' %>
          </div>
        </div>
      </div>
    </div>          
  </li>
  <li>
    <a href="/product">Products</a>
  </li>
  <li>
    <a href="/categories">Categories</a>
  </li>
  <li class="divider"></li>
  <li>
    <%= link_to 'About', '/about' %>
  </li>
  <li>
    <%= link_to 'Contact', '/contact' %>
  </li>
  <li class="divider"></li>
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Log In', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Sign Up', new_user_registration_path %>
    </li>
  <% end %>
  <li class="divider"></li>
  <li>
    <a>
      <i class="material-icons left">shopping_cart</i><%= @shopping_cart.size %>
    </a>
  </li>
  <li>
    <% if @shopping_cart.size > 0 %>
      <button class="btn checkout_button">Checkout</button>
      <li class="divider"></li>
      <%= link_to 'Empty Cart?', clear_cart_product_index_path, method: :post, class: "btn clear_cart_button"%>
    <% end %>
  </li>
</ul>


<!-- Main HTML of the page -->
<nav class="nav-colour">
  <div class="shaner-container">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Shop For Stuffs</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down" style="height: 30px;">
          <li style="height: 30px;">    
            <div class="center row">
              <div class="col s12" style="height: 30px;">
                <div class="row">
                  <div class="input-field col s6 s12">
                    
                    <%= render 'layouts/search' %>

                  </div>
                </div>
              </div>
            </div>          
          </li>
          <!-- Dropdown Trigger -->
          <li><a class="dropdown-trigger" data-belowOrigin="true" data-target="dropdown">
              Browse<i class="material-icons right">arrow_drop_down</i></a>
          </li>
          <li>
            <%= link_to 'About', '/about' %>
          </li>
          <li>
            <%= link_to 'Contact', '/contact' %>
          </li>
          
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Log In', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
          <% end %>

          <li>
            <a class="dropdown-trigger" data-belowOrigin="true" data-target="dropdown">
              <i class="material-icons left">shopping_cart</i><span class="new badge teal lighten-2" data-badge-caption="in cart"><%= @shopping_cart.size %></span>
            </a>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_tag(results_search_index_path, method: "get", class: "formsearch" ) do %>
                    
    <%= collection_select(:search, :category, Category.order(:title), :id, :title, {:include_blank => 'All'}, {:class=>"category-select"}) %>

    <%= text_field_tag(:q, "", class: "searchform") %>
    <button class="btn teal lighten-2 waves-effect waves-light" type="submit" name="action">
    <i class="material-icons searchicon">search</i></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopForStuff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% if flash %>
        <%= render 'layouts/flash_messages' %>
      <% end %>
      
      <div class="shaner-margins">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>

    <!--
    <%= debug session[:cart] %>
    <p>You've visited this site <%= pluralize @visit_count, 'time' %></p>-->
  </body>
</html>

app/views/pages/show.html.erb
<h4><%= @page.title %></h4>

<div><%= @page.content %></div>

app/views/random/card_grid.html.erb
<!--
    GRID OF 3 CARDS NICELY ALIGNED.
    inline-block class = display: inline-block
-->

<!--<div class="row inline-block">
    <div class="col s12 m4">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">Card Title</span>
                <p>I am a very simple card. I am good at containing small bits of information.
                I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
                <a href="#">This is a link</a>
                <a href="#">This is a link</a>
            </div>
        </div>
    </div>

    <div class="col s12 m4">
        <div class="card blue-grey darken-2">
            <div class="card-content white-text">
                <span class="card-title">Card Title</span>
                <p>I am a very simple card. I am good at containing small bits of information.
                I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
                <a href="#">This is a link</a>
                <a href="#">This is a link</a>
            </div>
        </div>
    </div>

    <div class="col s12 m4">
        <div class="card blue-grey lighten-1">
            <div class="card-content white-text">
                <span class="card-title">Card Title</span>
                <p>I am a very simple card. I am good at containing small bits of information.
                I am convenient because I require little markup to use effectively.</p>
            </div>
            <div class="card-action">
                <a href="#">This is a link</a>
                <a href="#">This is a link</a>
            </div>
        </div>
    </div>
</div>
-->